version: '3.8'

services:
  app:
    image: maxitwit/app
    build: ./
    container_name: maxitwit
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - NODE_PATH=/src/node_modules
    ports:
      - "127.0.0.1:3000:3000"
